"use strict";

module.exports = {
	MoveTypes: {
		QUIET: 0,
		DOUBLE_PAWN_PUSH: 1,
		KING_CASTLE: 2,
		QUEEN_CASTLE: 3,
		CAPTURE: 4,
		EN_PASSANT_CAPTURE: 5,
		KNIGHT_PROMOTION: 8,
		BISHOP_PROMOTION: 9,
		ROOK_PROMOTION: 10,
		QUEEN_PROMOTION: 11,
		KNIGHT_PROMOTION_CAPTURE: 12,
		BISHOP_PROMOTION_CAPTURE: 13,
		ROOK_PROMOTION_CAPTURE: 14,
		QUEEN_PROMOTION_CAPTURE: 15
	}
}